# Generated by Django 3.2.13 on 2022-07-07 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 13, 57, 625233, tzinfo=utc)),
        ),
    ]
